#!/usr/bin/env bash
# qc-notion-doc-standard.sh — machine-enforce the Notion Client-Doc Standard.
#
# WHY THIS EXISTS
# ---------------
# references/notion-client-doc-standard.md is the single standard for the client
# Quick-Start Notion setup doc (the Client Reference Sheet) generated by
# scripts/21-generate-client-reference-sheet.sh. Prose is not enforcement — this
# gate asserts the standard doc still CARRIES its hard §0 ordered mandatory list
# ("EVERY CLIENT NOTION SETUP DOC MUST INCLUDE ALL OF THE FOLLOWING, IN THIS
# ORDER") and every one of its 12 required items (Quick-Start first, the two-block
# Authorization, the two-block Content-Type, the FLAT 23-key Raw Body,
# tags-first + manual-fill + Build-with-AI-shape-only warning + post-build VERIFY,
# the Communication Playbooks section, VPS-vs-Mac, how-it-works LAST, each value in
# its own code block, Telegram delivery, and the universal no-personal-data rule).
#
# It then COMPOSES with scripts/qc-reference-sheet.sh — the gate that drives the
# generator in a sandbox and FAILs if the actually-RENDERED doc is missing any of
# those items. So this gate proves BOTH: (1) the standard is documented, and (2)
# the generator still produces a conforming doc.
#
# Exit codes: 0 = standard documented + generated doc conforms; 1 = the standard
# doc is missing a mandatory element OR the generated doc fails; 2 = bad usage.
#
# PURE BASH (grep) for the doc checks; delegates the rendered-doc check to
# qc-reference-sheet.sh. Respects qc-static.yml's .py claude-/anthropic scan (this
# file has no python). bash -n clean. set -uo pipefail.

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILL_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

while [ $# -gt 0 ]; do
  case "$1" in
    --skill-dir) SKILL_DIR="$2"; shift 2 ;;
    -h|--help)   sed -n '1,32p' "$0"; exit 0 ;;
    *) echo "Unknown arg: $1" >&2; exit 2 ;;
  esac
done

DOC="$SKILL_DIR/references/notion-client-doc-standard.md"

echo "=== qc-notion-doc-standard: Notion Client-Doc Standard gate ==="
echo "doc: $DOC"

if [ ! -f "$DOC" ]; then
  echo "RESULT: FAIL — notion-client-doc-standard.md is MISSING."
  exit 1
fi

FAIL=0
need() {  # need "<label>" "<grep -E pattern>"
  local label="$1" pat="$2"
  if grep -qE -- "$pat" "$DOC"; then
    echo "  [PASS] $label"
  else
    echo "  [FAIL] $label  (pattern: $pat)"
    FAIL=1
  fi
}

# The hard §0 ordered-mandatory-list headline.
need "§0 ordered-mandatory-list headline" 'EVERY CLIENT NOTION SETUP DOC MUST INCLUDE ALL OF THE FOLLOWING, IN THIS ORDER'

# The 12 ordered mandatory items.
need "(1) Quick Start FIRST"                          'Quick Start FIRST'
need "(2) Webhook URL — its own code block"           'Webhook URL .{0,3}.? its OWN code block|Webhook URL.*code block'
need "(3) Authorization as TWO separate code blocks"  'Authorization .{0,3}.? TWO separate code blocks|Authorization — TWO separate'
need "(3) block1 'Authorization' / block2 'Bearer <token>' value-only" 'Block 1 is exactly .?Authorization|exactly .?Bearer <token>'
need "(3) NEVER a combined Authorization: Bearer block" 'NEVER.{0,3}a combined .?Authorization: Bearer|combined .?Authorization: Bearer'
need "(4) Content-Type as two code blocks"            'Content-Type .{0,3}.? TWO separate code blocks|Content-Type — TWO separate'
need "(5) the FLAT 23-key Raw Body (own json block)"  'FLAT 23-key Raw Body'
need "(6) tags FIRST"                                 'tags FIRST'
need "(6) field-by-field manual fill"                 'field-by-field manual'
need "(6) Build-with-AI builds the SHAPE only warning" 'Build-with-AI builds the SHAPE only|builds the SHAPE only'
need "(6) post-build VERIFY checklist"                'post-build VERIFY'
need "(7) Your Communication Playbooks section"       'Your Communication Playbooks'
need "(7) help me build a [purpose] playbook CTA"     'help me build a \[purpose\] playbook|Just ask me'
need "(7) trigger-word + I-Do/You-Do + brainstorm"    'trigger word.*I Do / You Do|I Do / You Do.*brainstorm|trigger word'
need "(8) VPS-vs-Mac install considerations"          'VPS-vs-Mac install considerations|VPS .Hostinger Docker. vs Mac'
need "(9) How-it-works explanation LAST"              'How-it-works explanation LAST'
need "(10) every copyable value in its own code block" 'Every copyable value in its OWN code block|its OWN code block'
need "(11) delivered to the client via Telegram"     'Delivered to the client via Telegram|sent to the client via.*Telegram'
need "(12) UNIVERSAL — no personal/client data"       'UNIVERSAL .{0,3}.? no personal/client data|no personal/client data'

# Reference to the generator + the enforcing gates.
need "references 21-generate-client-reference-sheet.sh (generator)" '21-generate-client-reference-sheet.sh'
need "references qc-reference-sheet.sh (rendered-doc gate)"         'qc-reference-sheet.sh'
need "references qc-notify-client-doc.sh (Telegram delivery gate)"  'qc-notify-client-doc.sh'

echo ""
echo "--- composing with qc-reference-sheet.sh (drives the generator, checks the RENDERED doc) ---"
QC_REF="$SCRIPT_DIR/qc-reference-sheet.sh"
if [ -f "$QC_REF" ]; then
  if bash "$QC_REF" >/dev/null 2>&1; then
    echo "  [PASS] the generated client doc conforms (Quick-Start first, split Authorization/Content-Type, 23-key body, manual-fill, verify, playbooks, VPS-vs-Mac)"
  else
    echo "  [FAIL] qc-reference-sheet.sh found the generated doc missing a required item — run it directly"
    FAIL=1
  fi
else
  echo "  [FAIL] qc-reference-sheet.sh not found (cannot compose)"
  FAIL=1
fi

echo ""
if [ "$FAIL" -eq 0 ]; then
  echo "RESULT: PASS — the Notion Client-Doc Standard is documented and the generated doc conforms."
  exit 0
else
  echo "RESULT: FAIL — the Notion Client-Doc Standard is incomplete or the generated doc fails (see above)."
  exit 1
fi
