#!/usr/bin/env python3
"""
seed-workspaces.py
Seeds department workspaces into the Mission Control database.
Reads departments dynamically from:
  1. config/departments.json (generated by Skill 23)
  2. Falls back to scanning Skill 23 workspace folders

Run this after the Command Center is installed and the DB is created.
"""
import sqlite3, json, os, sys
from pathlib import Path

def find_db():
    candidates = [
        Path.home() / "projects/mission-control/mission-control.db",
        Path("/opt/mission-control/mission-control.db"),
        Path("/app/mission-control.db"),
    ]
    for p in candidates:
        if p.exists():
            return str(p)
    return None

def find_departments_config():
    """Look for departments.json generated by Skill 23"""
    candidates = [
        Path.home() / "projects/mission-control/config/departments.json",
        Path("/opt/mission-control/config/departments.json"),
        Path("/app/config/departments.json"),
    ]
    for p in candidates:
        if p.exists():
            with open(p) as f:
                data = json.load(f)
            if data:  # Not empty
                return data, str(p)
    return None, None

def scan_skill23_workspaces():
    """Fall back: scan Skill 23 workspace folders to build department list"""
    workspace_dirs = [
        Path.home() / ".openclaw/workspaces/command-center",
        Path.home() / "Downloads/openclaw-master-files/my AI company departments",
    ]
    
    # Default emoji map
    emoji_map = {
        'marketing': '📢', 'sales': '💰', 'billing': '💳', 'finance': '💳',
        'support': '🛟', 'operations': '⚙️', 'hr': '👥', 'creative': '🎨',
        'graphics': '🖼️', 'video': '🎬', 'audio': '🎵', 'legal': '⚖️',
        'technology': '💻', 'it': '💻', 'product': '🚀', 'research': '🔬',
        'training': '📚', 'ceo': '👔', 'com': '👔', 'analytics': '📊',
    }
    
    departments = []
    for ws_dir in workspace_dirs:
        if not ws_dir.exists():
            continue
        for folder in sorted(ws_dir.iterdir()):
            if folder.is_dir() and not folder.name.startswith('.'):
                dept_id = folder.name.lower().replace(' ', '-')
                dept_name = folder.name.replace('-', ' ').replace('_', ' ').title()
                # Try to read name from SOUL.md if it exists
                soul = folder / "SOUL.md"
                if soul.exists():
                    with open(soul) as f:
                        for line in f:
                            if line.startswith('# '):
                                dept_name = line.strip('# \n')
                                break
                emoji = '📁'
                for key, icon in emoji_map.items():
                    if key in dept_id:
                        emoji = icon
                        break
                departments.append({
                    'id': dept_id,
                    'name': dept_name,
                    'emoji': emoji
                })
        if departments:
            break  # Use first directory that has departments
    
    return departments

def find_company_info():
    """Try to find client company name from Skill 23 output"""
    answer_files = [
        Path.home() / "Downloads/openclaw-master-files/company-discovery/workforce-interview-answers.md",
        Path.home() / ".openclaw/workspace/company-discovery/workforce-interview-answers.md",
    ]
    company_name = "My Company"
    for f in answer_files:
        if f.exists():
            with open(f) as fh:
                for line in fh:
                    if 'company name' in line.lower() or 'business name' in line.lower():
                        # Next line might have the answer
                        next_line = next(fh, '').strip()
                        if next_line and not next_line.startswith('#'):
                            company_name = next_line
                            break
    return company_name

def seed(db_path, departments, company_name):
    conn = sqlite3.connect(db_path)
    cur = conn.cursor()

    # Ensure tables exist
    cur.execute("""
        CREATE TABLE IF NOT EXISTS companies (
            id TEXT PRIMARY KEY,
            name TEXT NOT NULL,
            slug TEXT UNIQUE NOT NULL,
            industry TEXT,
            config TEXT DEFAULT '{}'
        )
    """)
    cur.execute("""
        CREATE TABLE IF NOT EXISTS workspaces (
            id TEXT PRIMARY KEY,
            name TEXT NOT NULL,
            slug TEXT UNIQUE NOT NULL,
            description TEXT,
            icon TEXT,
            company_id TEXT DEFAULT 'default'
        )
    """)

    # Create company entry
    company_slug = company_name.lower().replace(' ', '-').replace("'", '')
    cur.execute(
        "INSERT OR IGNORE INTO companies (id, name, slug, industry, config) VALUES (?, ?, ?, ?, ?)",
        (company_slug, company_name, company_slug, '', '{}')
    )
    print(f"  Company: {company_name} ({company_slug})")

    existing = {row[0] for row in cur.execute("SELECT id FROM workspaces").fetchall()}
    inserted = 0
    skipped = 0

    for dept in departments:
        dept_id = dept['id']
        if dept_id in existing:
            skipped += 1
            continue
        cur.execute("""
            INSERT INTO workspaces (id, name, slug, description, icon, company_id)
            VALUES (?, ?, ?, ?, ?, ?)
        """, (
            dept_id,
            dept['name'],
            dept_id,
            f"{dept['name']} department workspace",
            dept.get('emoji', '📁'),
            company_slug
        ))
        print(f"  INSERTED: {dept_id} ({dept['name']}) {dept.get('emoji', '📁')}")
        inserted += 1

    conn.commit()
    conn.close()
    print(f"\nSeeding complete. Inserted: {inserted} | Skipped (already existed): {skipped}")

if __name__ == "__main__":
    db = find_db()
    if not db:
        print("ERROR: Could not find mission-control.db. Is the Command Center installed?")
        sys.exit(1)

    # Try departments.json first, fall back to scanning folders
    departments, source = find_departments_config()
    if departments:
        print(f"Source: {source}")
    else:
        print("departments.json empty or missing. Scanning Skill 23 workspace folders...")
        departments = scan_skill23_workspaces()
        source = "Skill 23 workspace scan"

    if not departments:
        print("ERROR: No departments found. Run Skill 23 (AI Workforce Blueprint) first.")
        sys.exit(1)

    company_name = find_company_info()
    
    print(f"DB: {db}")
    print(f"Source: {source}")
    print(f"Company: {company_name}")
    print(f"Departments found: {len(departments)}")
    print("Seeding workspaces...")
    seed(db, departments, company_name)
