#!/usr/bin/env python3
"""
seed-workspaces.py
Seeds department workspaces into the Mission Control database.
Reads departments dynamically from:
  1. config/departments.json (generated by Skill 23)
  2. Falls back to scanning Skill 23 workspace folders

Run this after the Command Center is installed and the DB is created.
"""
import sqlite3, json, os, sys, re
from pathlib import Path

def find_db():
    candidates = [
        Path.home() / "projects/command-center/mission-control.db",
        Path.home() / "projects/mission-control/mission-control.db",
        Path("/opt/mission-control/mission-control.db"),
        Path("/app/mission-control.db"),
    ]
    for p in candidates:
        if p.exists():
            return str(p)
    return None

def find_departments_config():
    """Look for departments.json generated by Skill 23"""
    candidates = [
        Path.home() / "Downloads/openclaw-master-files/company-discovery/departments.json",  # canonical (Skill 23 output)
        Path.home() / "projects/command-center/config/departments.json",
        Path.home() / "projects/mission-control/config/departments.json",
        Path.home() / "clawd/departments/departments.json",
        Path("/opt/mission-control/config/departments.json"),
        Path("/app/config/departments.json"),
    ]
    for p in candidates:
        if p.exists():
            with open(p) as f:
                data = json.load(f)
            if data:  # Not empty
                return data, str(p)
    return None, None

def scan_skill23_workspaces():
    """Fall back: scan Skill 23 workspace folders to build department list"""
    workspace_dirs = [
        Path.home() / "clawd/departments",
        Path.home() / ".openclaw/workspaces/command-center",
        Path.home() / "Downloads/openclaw-master-files/my AI company departments",
    ]
    # Also scan ~/Downloads/ for any department folders
    downloads = Path.home() / "Downloads"
    if downloads.exists():
        for item in sorted(downloads.iterdir()):
            if item.is_dir() and ('dept' in item.name.lower() or 'department' in item.name.lower()):
                workspace_dirs.append(item)
    
    # Default emoji map
    emoji_map = {
        'marketing': '📢', 'sales': '💰', 'billing': '💳', 'finance': '💳',
        'support': '🛟', 'operations': '⚙️', 'hr': '👥', 'creative': '🎨',
        'graphics': '🖼️', 'video': '🎬', 'audio': '🎵', 'legal': '⚖️',
        'technology': '💻', 'it': '💻', 'product': '🚀', 'research': '🔬',
        'training': '📚', 'ceo': '👔', 'com': '👔', 'analytics': '📊',
    }
    
    departments = []
    parent_folder_name = None
    
    for ws_dir in workspace_dirs:
        if not ws_dir.exists():
            continue
        # Store parent folder name as potential company name
        parent_folder_name = ws_dir.parent.name if ws_dir.name == "command-center" else ws_dir.name
        for folder in sorted(ws_dir.iterdir()):
            if folder.is_dir() and not folder.name.startswith('.'):
                raw_name = folder.name.lower().replace(' ', '-')
                # Strip "-dept" suffix that Skill 23 uses (e.g., "marketing-dept" -> "marketing")
                dept_id = re.sub(r'-dept$', '', raw_name)
                dept_name = dept_id.replace('-', ' ').replace('_', ' ').title()
                # Try to read name from SOUL.md if it exists
                soul = folder / "SOUL.md"
                if soul.exists():
                    with open(soul) as f:
                        for line in f:
                            if line.startswith('# '):
                                dept_name = line.strip('# \n')
                                break
                emoji = '📁'
                for key, icon in emoji_map.items():
                    if key in dept_id:
                        emoji = icon
                        break
                departments.append({
                    'id': dept_id,
                    'name': dept_name,
                    'emoji': emoji
                })
        if departments:
            break  # Use first directory that has departments
    
    return departments, parent_folder_name

def find_company_info(parent_folder_name=None):
    """Find company name from env var, interview answers, or parent folder"""
    # 1. Check COMPANY_NAME env var first
    company_name = os.environ.get("COMPANY_NAME", "").strip()
    if company_name:
        return company_name
    
    # 2. Try to find from Skill 23 interview answers
    answer_files = [
        Path.home() / "Downloads/openclaw-master-files/company-discovery/workforce-interview-answers.md",
        Path.home() / ".openclaw/workspace/company-discovery/workforce-interview-answers.md",
    ]
    
    for f in answer_files:
        if f.exists():
            try:
                with open(f) as fh:
                    content = fh.read()
                    # Look for patterns like "Company Name: XYZ" or "## Company Name\nXYZ"
                    patterns = [
                        r'(?:company|business)\s*name\s*[:\-]\s*(.+?)(?:\n|$)',
                        r'#+\s*(?:company|business)\s*name\s*\n+(.+?)(?:\n|$)',
                    ]
                    for pattern in patterns:
                        match = re.search(pattern, content, re.IGNORECASE)
                        if match:
                            company_name = match.group(1).strip()
                            if company_name:
                                return company_name
            except Exception:
                pass
    
    # 3. Use parent folder name if available
    if parent_folder_name and parent_folder_name not in ['workspaces', 'command-center']:
        # Clean up the folder name (remove common suffixes)
        clean_name = parent_folder_name.replace('-dept', '').replace('_dept', '')
        clean_name = clean_name.replace('-', ' ').replace('_', ' ').title()
        return clean_name
    
    # 4. Default fallback
    return "My Company"

def seed(db_path, departments, company_name):
    conn = sqlite3.connect(db_path)
    cur = conn.cursor()

    # Ensure tables exist
    cur.execute("""
        CREATE TABLE IF NOT EXISTS companies (
            id TEXT PRIMARY KEY,
            name TEXT NOT NULL,
            slug TEXT UNIQUE NOT NULL,
            industry TEXT,
            config TEXT DEFAULT '{}'
        )
    """)
    cur.execute("""
        CREATE TABLE IF NOT EXISTS workspaces (
            id TEXT PRIMARY KEY,
            name TEXT NOT NULL,
            slug TEXT UNIQUE NOT NULL,
            description TEXT,
            icon TEXT,
            company_id TEXT DEFAULT 'default'
        )
    """)

    # Create company entry
    company_slug = re.sub(r'[^a-z0-9]+', '-', company_name.lower()).strip('-')
    if not company_slug:
        company_slug = 'my-company'
    
    cur.execute(
        "INSERT OR IGNORE INTO companies (id, name, slug, industry, config) VALUES (?, ?, ?, ?, ?)",
        (company_slug, company_name, company_slug, '', '{}')
    )
    print(f"  Company: {company_name} ({company_slug})")

    existing = {row[0] for row in cur.execute("SELECT id FROM workspaces").fetchall()}
    inserted = 0
    skipped = 0

    for dept in departments:
        dept_id = dept['id']
        if dept_id in existing:
            skipped += 1
            continue
        cur.execute("""
            INSERT INTO workspaces (id, name, slug, description, icon, company_id)
            VALUES (?, ?, ?, ?, ?, ?)
        """, (
            dept_id,
            dept['name'],
            dept_id,
            f"{dept['name']} department workspace",
            dept.get('emoji', '📁'),
            company_slug
        ))
        print(f"  INSERTED: {dept_id} ({dept['name']}) {dept.get('emoji', '📁')}")
        inserted += 1

    conn.commit()
    conn.close()
    print(f"\nSeeding complete. Inserted: {inserted} | Skipped (already existed): {skipped}")

if __name__ == "__main__":
    db = find_db()
    if not db:
        print("ERROR: Could not find mission-control.db. Is the Command Center installed?")
        sys.exit(1)

    # Try departments.json first, fall back to scanning folders
    departments, source = find_departments_config()
    parent_folder_name = None
    
    if departments:
        print(f"Source: {source}")
    else:
        print("departments.json empty or missing. Scanning Skill 23 workspace folders...")
        departments, parent_folder_name = scan_skill23_workspaces()
        source = "Skill 23 workspace scan"

    if not departments:
        print("ERROR: No departments found. Run Skill 23 (AI Workforce Blueprint) first.")
        sys.exit(1)

    company_name = find_company_info(parent_folder_name)
    
    print(f"DB: {db}")
    print(f"Source: {source}")
    print(f"Company: {company_name}")
    print(f"Departments found: {len(departments)}")
    print("Seeding workspaces...")
    seed(db, departments, company_name)
